ONBOARDING_STATUSES = (
    "Not Started",
    "In Progress",
    "Awaiting Review",
    "Complete",
    "Rejected",
    "Overdue",
)

DEFAULT_ONBOARDING_STATUS = "Not Started"

DEFAULT_ONBOARDING_STEPS = (
    {
        "sort_order": 1,
        "title": "Create account",
        "description": "Agent creates their portal login account.",
        "required": True,
        "approval_required": False,
    },
    {
        "sort_order": 2,
        "title": "Complete personal profile",
        "description": "Agent completes their contact, business, address, and bank details.",
        "required": True,
        "approval_required": False,
    },
    {
        "sort_order": 3,
        "title": "Upload ID document",
        "description": "Agent uploads a valid ID document for review.",
        "required": True,
        "approval_required": True,
    },
    {
        "sort_order": 4,
        "title": "Upload proof of address",
        "description": "Agent uploads proof of address for review.",
        "required": True,
        "approval_required": True,
    },
    {
        "sort_order": 5,
        "title": "Add bank details for commission payments",
        "description": "Agent adds bank details so commission payments can be processed later.",
        "required": True,
        "approval_required": True,
    },
    {
        "sort_order": 6,
        "title": "Sign contractor agreement",
        "description": "Agent signs the contractor agreement.",
        "required": True,
        "approval_required": True,
    },
    {
        "sort_order": 7,
        "title": "Accept membership terms",
        "description": "Agent accepts the membership terms.",
        "required": True,
        "approval_required": False,
    },
    {
        "sort_order": 8,
        "title": "Pay setup fee",
        "description": "Setup fee is marked as paid.",
        "required": True,
        "approval_required": True,
    },
    {
        "sort_order": 9,
        "title": "Set up recurring membership payment",
        "description": "Recurring membership payment is set up.",
        "required": True,
        "approval_required": True,
    },
    {
        "sort_order": 10,
        "title": "Attend welcome call",
        "description": "Agent attends the welcome call.",
        "required": True,
        "approval_required": True,
    },
    {
        "sort_order": 11,
        "title": "Attend compliance call",
        "description": "Agent attends the compliance call.",
        "required": True,
        "approval_required": True,
    },
    {
        "sort_order": 12,
        "title": "Complete compliance training",
        "description": "Agent completes mandatory compliance training.",
        "required": True,
        "approval_required": True,
    },
    {
        "sort_order": 13,
        "title": "Complete CRM training",
        "description": "Agent completes CRM system training.",
        "required": True,
        "approval_required": True,
    },
    {
        "sort_order": 14,
        "title": "Complete supplier training",
        "description": "Agent completes supplier training.",
        "required": True,
        "approval_required": True,
    },
    {
        "sort_order": 15,
        "title": "Accept social media and advertising policy",
        "description": "Agent accepts the social media and advertising policy.",
        "required": True,
        "approval_required": False,
    },
    {
        "sort_order": 16,
        "title": "Complete final assessment",
        "description": "Agent completes the final assessment.",
        "required": True,
        "approval_required": True,
    },
    {
        "sort_order": 17,
        "title": "Admin final approval",
        "description": "Admin gives final approval before the agent can trade.",
        "required": True,
        "approval_required": True,
    },
)
