TRAINING_CATEGORIES = (
    "Welcome",
    "Compliance",
    "Systems",
    "Sales",
    "Supplier",
    "Marketing",
    "Cruise",
    "Disney",
    "Luxury Travel",
    "Group Bookings",
    "Further Training",
    "Leadership",
    "Refresher Training",
)

TRAINING_PUBLISHED_STATUSES = (
    "Draft",
    "Published",
    "Archived",
)

TRAINING_PROGRESS_STATUSES = (
    "Not Started",
    "In Progress",
    "Complete",
    "Failed",
    "Expired",
)

TRAINING_TRACKS = (
    "Onboarding",
    "Further Training",
)

DEFAULT_TRAINING_PUBLISHED_STATUS = "Draft"
DEFAULT_TRAINING_PROGRESS_STATUS = "Not Started"
DEFAULT_TRAINING_TRACK = "Onboarding"
FURTHER_TRAINING_TRACK = "Further Training"

FURTHER_TRAINING_CATEGORIES = (
    "Sales Development",
    "Destination Knowledge",
    "Supplier Training",
    "Cruise Training",
    "Disney Training",
    "Luxury Travel",
    "Group Bookings",
    "Marketing",
    "Compliance Refreshers",
    "Leadership Training",
    "Systems Refreshers",
)

DEFAULT_MANDATORY_MODULES = (
    {
        "title": "Welcome to One Travel Club",
        "description": "Introduction to the One Travel Club brand, team, and onboarding journey.",
        "category_name": "Welcome",
        "level": "Beginner",
        "mandatory": True,
        "estimated_completion_time": "30 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Introduction to Travel Sales",
        "description": "Basic travel sales principles and customer conversation structure.",
        "category_name": "Sales",
        "level": "Beginner",
        "mandatory": True,
        "estimated_completion_time": "45 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Introduction to Package Holidays",
        "description": "Overview of package holidays and how they are sold responsibly.",
        "category_name": "Supplier",
        "level": "Beginner",
        "mandatory": True,
        "estimated_completion_time": "45 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "TTA & ATOL Basics",
        "description": "Introductory training on TTA and ATOL protection basics.",
        "category_name": "Compliance",
        "level": "Beginner",
        "mandatory": True,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": True,
        "pass_mark": 80,
        "certificate_issued": True,
        "renewal_required": True,
        "renewal_period_months": 12,
        "published_status": "Published",
    },
    {
        "title": "Compliance & Customer Money",
        "description": "How agents must handle compliance, payments, and customer money rules.",
        "category_name": "Compliance",
        "level": "Beginner",
        "mandatory": True,
        "estimated_completion_time": "90 minutes",
        "content_type": "Text",
        "quiz_required": True,
        "pass_mark": 80,
        "certificate_issued": True,
        "renewal_required": True,
        "renewal_period_months": 12,
        "published_status": "Published",
    },
    {
        "title": "CRM Training",
        "description": "How to use the customer relationship management system.",
        "category_name": "Systems",
        "level": "Beginner",
        "mandatory": True,
        "estimated_completion_time": "60 minutes",
        "content_type": "Video",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Supplier Training",
        "description": "How to work with approved suppliers and supplier portals.",
        "category_name": "Supplier",
        "level": "Beginner",
        "mandatory": True,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Quoting & Booking Process",
        "description": "The approved quote, booking, and follow-up process.",
        "category_name": "Systems",
        "level": "Beginner",
        "mandatory": True,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Customer Service Standards",
        "description": "Expected service standards for all One Travel Club customers.",
        "category_name": "Sales",
        "level": "Beginner",
        "mandatory": True,
        "estimated_completion_time": "45 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Social Media & Advertising Policy",
        "description": "Approved marketing, advertising, and social media rules.",
        "category_name": "Marketing",
        "level": "Beginner",
        "mandatory": True,
        "estimated_completion_time": "45 minutes",
        "content_type": "Text",
        "quiz_required": True,
        "pass_mark": 80,
        "certificate_issued": False,
        "renewal_required": True,
        "renewal_period_months": 12,
        "published_status": "Published",
    },
    {
        "title": "Data Protection & GDPR",
        "description": "Basic data protection and GDPR responsibilities for agents.",
        "category_name": "Compliance",
        "level": "Beginner",
        "mandatory": True,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": True,
        "pass_mark": 80,
        "certificate_issued": True,
        "renewal_required": True,
        "renewal_period_months": 12,
        "published_status": "Published",
    },
    {
        "title": "Final Assessment",
        "description": "Final onboarding assessment before approval to trade.",
        "category_name": "Welcome",
        "level": "Beginner",
        "mandatory": True,
        "estimated_completion_time": "60 minutes",
        "content_type": "Quiz",
        "quiz_required": True,
        "pass_mark": 80,
        "certificate_issued": True,
        "renewal_required": False,
        "published_status": "Published",
    },
)

DEFAULT_FURTHER_TRAINING_MODULES = (
    {
        "title": "Closing Techniques",
        "description": "Optional sales development training on closing conversations confidently.",
        "category_name": "Sales Development",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "45 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Objection Handling",
        "description": "Optional sales training for handling common customer objections.",
        "category_name": "Sales Development",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "45 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Upselling Travel Extras",
        "description": "Optional training on presenting extras that improve the customer trip.",
        "category_name": "Sales Development",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "45 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "USA Destination Training",
        "description": "Optional destination knowledge training for USA holidays.",
        "category_name": "Destination Knowledge",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Caribbean Destination Training",
        "description": "Optional destination knowledge training for Caribbean holidays.",
        "category_name": "Destination Knowledge",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Dubai Destination Training",
        "description": "Optional destination knowledge training for Dubai holidays.",
        "category_name": "Destination Knowledge",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Maldives Destination Training",
        "description": "Optional destination knowledge training for Maldives holidays.",
        "category_name": "Destination Knowledge",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Royal Caribbean Training",
        "description": "Optional supplier training for Royal Caribbean cruises.",
        "category_name": "Cruise Training",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "MSC Cruises Training",
        "description": "Optional supplier training for MSC Cruises.",
        "category_name": "Cruise Training",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Virgin Voyages Training",
        "description": "Optional supplier training for Virgin Voyages.",
        "category_name": "Cruise Training",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Walt Disney World Training",
        "description": "Optional destination and supplier training for Walt Disney World.",
        "category_name": "Disney Training",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Disneyland Paris Training",
        "description": "Optional destination and supplier training for Disneyland Paris.",
        "category_name": "Disney Training",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Facebook Lead Generation",
        "description": "Optional marketing training for generating leads on Facebook.",
        "category_name": "Marketing",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "45 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Email Marketing for Travel Agents",
        "description": "Optional marketing training for email campaigns and follow-up.",
        "category_name": "Marketing",
        "level": "Intermediate",
        "mandatory": False,
        "estimated_completion_time": "45 minutes",
        "content_type": "Text",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
    {
        "title": "Annual Compliance Refresher",
        "description": "Optional refresher training for annual compliance knowledge.",
        "category_name": "Compliance Refreshers",
        "level": "Refresher",
        "mandatory": False,
        "estimated_completion_time": "60 minutes",
        "content_type": "Text",
        "quiz_required": True,
        "pass_mark": 80,
        "certificate_issued": True,
        "renewal_required": True,
        "renewal_period_months": 12,
        "published_status": "Published",
    },
    {
        "title": "Advanced CRM Training",
        "description": "Optional systems refresher for advanced CRM features.",
        "category_name": "Systems Refreshers",
        "level": "Advanced",
        "mandatory": False,
        "estimated_completion_time": "60 minutes",
        "content_type": "Video",
        "quiz_required": False,
        "certificate_issued": False,
        "renewal_required": False,
        "published_status": "Published",
    },
)
